### ISSUE TITLE
Chroot does not install

### ISSUE THREAD

**Issue by ghost** [johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#2]
When I try to install the chroot, it tells me that I have successfully installed it, but when I launch the terminal, it can't find any files in the nhsystem folder.

**Comment by johanlike** [comment]
Please note that if you download arm64, amd64, i386 bit version of kalifs-full.tar.xz, you will need to change the file name in the package to armhf. If you do not change, nh terminal and nethunter will not be recognized and installed properly. I have already raised this question in the description...

**Comment by ghost** [comment]
I can't read the description, and also, I renamed the file to kalifs-full.tar.xz, otherwise, it doesn't recognize the file is there

**Comment by johanlike** [comment]
Open kalifs-full.tar.xz and change kali-xxxx to kali-armhf

**Comment by ghost** [comment]
Are you meaning **inside** the file or renaming the file? Because I renamed it and when using the Chroot Manager it tells me, "Error: Missing file: /storage/emulated/0/kalifs-full.tar.xz not found"

**Comment by szEIgo** [comment]
> Are you meaning **inside** the file or renaming the file? Because I renamed it and when using the Chroot Manager it tells me, "Error: Missing file: /storage/emulated/0/kalifs-full.tar.xz not found"

In his pictures it looks like its depending the kalifs to be kali-armhf, check install3.jpg

**Comment by johanlike** [comment]
@szEIgo @0o0will0o0 Ok, when I updated the system today, when I tried to use kalifs-full.tar.xz to brush into kali, I found that the new nethunter app couldn't extract kalifs-full.tar.xz. Most of the time I have installed kali with the linux deploy app, so I am sorry to find this problem now. Because I need to go to work. So I will solve this problem later. This is the temporary solution I gave.（already fixed）
~~adb push kalifs-full.tar.xz /sdcard/ 
adb shell
su
mv  /sdcard/kalifs-full.tar.xz /data/local/nhsystem/
cd /data/local/nhsystem/
xz -d  kalifs-full.tar.xz
tar xvf kalifs-full.tar~~

**Comment by 0o0will0o0** [comment]
So I did the listed commands, but when I open the nethunter app, it tells
me that the chroot is not found and then proceeds to "clean the
installation folder" thus undoing everything and wiping the unpacked tar.xz

**Comment by johanlike** [comment]
The nethunter app has been fixed and does not need to modify the file name in the package. It supports multiple architectures of tar.xz arm64 amd64 i386..

**Comment by ASASA277Hydra** [comment]
thank u for u good job!!    N1ce
