### ISSUE TITLE
Little trouble understanding the Installation guide. 

### ISSUE THREAD

**Issue by szEIgo** [johanlike/DJY-Oneplus6-or-Oneplus6T-Nethunter-Andrax-Kernel#3]
First of all, thank you aot for your effort! I really appreciate the work you have done!

If i am understanding the guide correctly, this is what i would try to do.

1) wipe whole system
2) Flash twrp
3) Flash Oxygen Os 9.0.12
4) extract payload-dumper-linux.zip
5) Flash whats inside the payload package with TWRP
6) run Flash.sh?? This deletes all?
7) sideload djy kernel
8) reboot
9) open magisk and update

I have tried this partly, but after executing the Flash.sh all my data is lost, and i now have permission issues with fastboot.

I know all this is stupid questions - i am a newbie but I would really like the functionality without compromising too much stability.

Thanks!

**Comment by johanlike** [comment]
@szEIgo Hello brother, your system turned out to be OOS. Why use flash.bat or falsh.sh? These two scripts are used to refresh the Chinese user HOS system to the OOS system. If you turned out to be OOS, then you don't need to refresh, just brush into the kernel, then open the magiskapp update and brush it into the WIFI module.

If you need to refresh your system to a brand new OOS, you can also use the two scripts above, but be careful to save your personal data as this will erase everything on the phone.

It should be noted here that if you are using payload-dumper-WIN, you will need to download a new version of fastboot. Otherwise, the fastboot version may be too low to be able to get into the image file.
Below is the download link：
`https://developer.android.com/studio/releases/platform-tools`

**Comment by szEIgo** [comment]
@Johanlike thank you alot!
You are the best!

**Comment by Hadesink** [comment]
@johanlike  Can I brush the kernal with twrp currently adb doesn't recognize my device in fastboot mode 
Also  I'm trying to get my wireless card work with ANDRAX not nethunter. PS total noob questions 😅

**Comment by Hadesink** [comment]
@johanlike quick update I  flashed the kernel and the wifi package. Now I can use my WiFi card to capture packets . I'm using ANDRAX and not nethunter and I happy to report it works . Thanks man I appreciate your work . Keep up the good work👍
